name: "同步 GitHub Labels"

on:
  push:
    branches:
      - master
    paths:
      - '.github/labels.yml'
  workflow_dispatch: # 允许手动触发

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 代码
        uses: actions/checkout@v6

      - name: 同步标签
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
          prune: false  # 设置为 true 会删除不在配置中的标签
